<?php get_header(); ?>

    <!-- ===== ABOUT HAEMOPHILIA PAGE ===== -->
    <div class="section" id="haemophilia" style="background:linear-gradient(135deg, #FAFBFE 0%, #F0F4FB 50%, #E8EEF8 100%)"><div class="container"><div class="split">
      <div data-reveal><h2 style="margin-bottom:var(--s-4)" data-i18n="haem_heading"><?php echo esc_html(cha_get_option('haem_intro_heading', 'What is Haemophilia?')); ?></h2>
      <p data-i18n="haem_para_1"><?php echo esc_html(cha_get_option('haem_intro_p1', "Haemophilia is a rare genetic bleeding disorder that affects a person's ability to stop bleeding. People with haemophilia can bleed longer than others after an injury or even without a known cause.")); ?></p>
      <p data-i18n="haem_para_2"><?php echo esc_html(cha_get_option('haem_intro_p2', 'While there is no cure, modern treatments allow people with haemophilia to live full, active and healthy lives. Early diagnosis, proper treatment and ongoing support are key to preventing complications and joint damage.')); ?></p>
      <a class="btn btn-secondary" href="<?php echo home_url('/#contact'); ?>" data-i18n="haem_contact"><?php echo esc_html(cha_get_option('haem_intro_btn', 'Contact a Specialist')); ?> <span class="arrow">→</span></a></div>
      <div class="split-illust" data-reveal><svg viewBox="0 0 200 240" width="280" height="280" aria-label="Blood drop"><defs><radialGradient id="drop-grad" cx="50%" cy="40%" r="60%"><stop offset="0%" stop-color="#FF6B6B"/><stop offset="100%" stop-color="#E31E24"/></radialGradient></defs><path d="M100 20 C 60 80, 30 130, 30 170 C 30 210, 60 230, 100 230 C 140 230, 170 210, 170 170 C 170 130, 140 80, 100 20 Z" fill="url(#drop-grad)"/><ellipse cx="78" cy="120" rx="14" ry="22" fill="rgba(255,255,255,0.35)"/></svg></div>
    </div></div></div>

    <div class="section section-soft"><div class="container">
      <div class="section-heading" data-reveal><h2 data-i18n="types_heading"><?php echo esc_html(cha_get_option('haem_types_heading', 'Types of Haemophilia')); ?></h2><p data-i18n="types_sub"><?php echo esc_html(cha_get_option('haem_types_sub', 'The two main types of haemophilia — both require proper diagnosis and lifelong management.')); ?></p></div>
      <div class="grid grid-2">
        <div class="type-card" data-reveal><div class="type-card-icon"><svg class="drop" viewBox="0 0 56 64" aria-hidden="true"><path d="M28 4 C 16 24, 8 38, 8 48 C 8 58, 18 64, 28 64 C 38 64, 48 58, 48 48 C 48 38, 40 24, 28 4 Z" fill="#E31E24"/><ellipse cx="20" cy="32" rx="4" ry="7" fill="rgba(255,255,255,0.4)"/></svg></div><div class="type-card-body"><h3 data-i18n="types_a_title"><?php echo esc_html(cha_get_option('haem_type_a_title', 'Haemophilia A')); ?></h3><p data-i18n="types_a_desc"><?php echo esc_html(cha_get_option('haem_type_a_desc', 'Caused by a deficiency of factor VIII. The most common type.')); ?></p></div></div>
        <div class="type-card" data-reveal><div class="type-card-icon"><svg class="drop" viewBox="0 0 56 64" aria-hidden="true"><path d="M28 4 C 16 24, 8 38, 8 48 C 8 58, 18 64, 28 64 C 38 64, 48 58, 48 48 C 48 38, 40 24, 28 4 Z" fill="#0B1D6D"/><ellipse cx="20" cy="32" rx="4" ry="7" fill="rgba(255,255,255,0.4)"/></svg></div><div class="type-card-body"><h3 data-i18n="types_b_title"><?php echo esc_html(cha_get_option('haem_type_b_title', 'Haemophilia B')); ?></h3><p data-i18n="types_b_desc"><?php echo esc_html(cha_get_option('haem_type_b_desc', 'Caused by a deficiency of factor IX. Sometimes called Christmas disease.')); ?></p></div></div>
      </div>
    </div></div>

    <div class="section symptoms-section"><div class="container">
      <div class="section-heading" data-reveal><h2 data-i18n="symptoms_heading"><?php echo esc_html(cha_get_option('haem_symptoms_heading', 'Common Symptoms')); ?></h2><p data-i18n="symptoms_sub"><?php echo esc_html(cha_get_option('haem_symptoms_sub', 'Recognizing the signs of a bleeding disorder is the first step toward diagnosis and proper care.')); ?></p></div>
      <div class="symptoms-grid">
        <div class="symptom-card" data-reveal><div class="icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="M8 14s1.5 2 4 2 4-2 4-2"/><line x1="9" y1="9" x2="9.01" y2="9"/><line x1="15" y1="9" x2="15.01" y2="9"/></svg></div><p class="label" data-i18n="symptom_bruising"><?php echo esc_html(cha_get_option('symptom_1_title', 'Easy Bruising')); ?></p><p class="hint" data-i18n="symptom_bruising_desc"><?php echo esc_html(cha_get_option('symptom_1_desc', 'Unexplained bruises from minor bumps or pressure.')); ?></p></div>
        <div class="symptom-card" data-reveal><div class="icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 2C8 2 6 5 6 8c0 4 6 12 6 12s6-8 6-12c0-3-2-6-6-6z"/><circle cx="12" cy="8" r="2"/></svg></div><p class="label" data-i18n="symptom_nosebleeds"><?php echo esc_html(cha_get_option('symptom_2_title', 'Frequent Nosebleeds')); ?></p><p class="hint" data-i18n="symptom_nosebleeds_desc"><?php echo esc_html(cha_get_option('symptom_2_desc', 'Recurring nosebleeds that are hard to stop.')); ?></p></div>
        <div class="symptom-card" data-reveal><div class="icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 2v20M2 12h20"/><circle cx="12" cy="12" r="4"/></svg></div><p class="label" data-i18n="symptom_gums"><?php echo esc_html(cha_get_option('symptom_3_title', 'Bleeding Gums')); ?></p><p class="hint" data-i18n="symptom_gums_desc"><?php echo esc_html(cha_get_option('symptom_3_desc', 'Gums that bleed during brushing or eating.')); ?></p></div>
        <div class="symptom-card" data-reveal><div class="icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M6 18h8"/><path d="M3 22h18"/><path d="M14 22a7 7 0 1 0 0-14h-1"/><path d="M9 14h2"/><path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2z"/><path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3"/></svg></div><p class="label" data-i18n="symptom_joint"><?php echo esc_html(cha_get_option('symptom_4_title', 'Joint Pain or Swelling')); ?></p><p class="hint" data-i18n="symptom_joint_desc"><?php echo esc_html(cha_get_option('symptom_4_desc', 'Painful, swollen joints after minor injury or activity.')); ?></p></div>
        <div class="symptom-card" data-reveal><div class="icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg></div><p class="label" data-i18n="symptom_prolonged"><?php echo esc_html(cha_get_option('symptom_5_title', 'Prolonged Bleeding')); ?></p><p class="hint" data-i18n="symptom_prolonged_desc"><?php echo esc_html(cha_get_option('symptom_5_desc', 'Bleeding that lasts longer than expected after cuts.')); ?></p></div>
      </div>
      <div class="symptoms-cta" data-reveal><p data-i18n="symptom_cta"><?php echo esc_html(cha_get_option('symptoms_cta', 'Experiencing any of these symptoms? Early diagnosis can make a life-changing difference.')); ?></p><div class="btn-row"><a class="btn btn-primary" href="<?php echo home_url('/programs'); ?>#treatment-centres" data-i18n="symptom_find_centre"><?php echo esc_html(cha_get_option('symptoms_btn_1', 'Find a Treatment Centre')); ?> <span class="arrow">→</span></a><a class="btn btn-secondary" href="<?php echo home_url('/#contact'); ?>" data-i18n="symptom_contact_specialist"><?php echo esc_html(cha_get_option('symptoms_btn_2', 'Contact a Specialist')); ?></a></div></div>
    </div></div>

    <section class="section section-soft" id="vwd"><div class="container">
      <div class="section-heading" data-reveal><h2 data-i18n="vwd_heading"><?php echo esc_html(cha_get_option('vwd_heading', 'Von Willebrand Disease (VWD)')); ?></h2></div>
      <div class="split"><div data-reveal><p data-i18n="vwd_para_1"><?php echo esc_html(cha_get_option('vwd_p1', 'Von Willebrand Disease is the most common inherited bleeding disorder, affecting both males and females equally. It is caused by a deficiency or dysfunction of von Willebrand factor, a protein that helps blood clot.')); ?></p><p data-i18n="vwd_para_2"><?php echo esc_html(cha_get_option('vwd_p2', 'There are three main types of VWD — Type 1 (mild), Type 2 (moderate), and Type 3 (severe). Treatment focuses on managing bleeding episodes and may include desmopressin or factor replacement therapy.')); ?></p><a class="btn btn-secondary" href="<?php echo home_url('/programs'); ?>#treatment-centres" data-i18n="vwd_find"><?php echo esc_html(cha_get_option('vwd_btn', 'Find Treatment')); ?> <span class="arrow">→</span></a></div><div class="split-illust" data-reveal><svg viewBox="0 0 240 240" width="260" height="260" aria-label="VWD blood factors illustration"><defs><linearGradient id="vwd-grad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#6A2C91"/><stop offset="100%" stop-color="#B07AD4"/></linearGradient></defs><circle cx="120" cy="120" r="100" fill="none" stroke="url(#vwd-grad)" stroke-width="2.5" stroke-dasharray="8 6"/><circle cx="120" cy="120" r="70" fill="none" stroke="var(--c-purple-100)" stroke-width="1.5"/><circle cx="85" cy="95" r="16" fill="#EFE6F4" stroke="var(--c-purple)" stroke-width="2"/><circle cx="155" cy="95" r="16" fill="#EFE6F4" stroke="var(--c-purple)" stroke-width="2"/><circle cx="120" cy="160" r="22" fill="var(--c-purple-100)" stroke="var(--c-purple)" stroke-width="2"/><line x1="85" y1="95" x2="155" y2="95" stroke="#D4C4E8" stroke-width="1"/><line x1="120" y1="111" x2="120" y2="138" stroke="#D4C4E8" stroke-width="1"/></svg></div></div>
    </div></section>

    <section class="section" id="other-bleeding"><div class="container">
      <div class="section-heading" data-reveal><h2 data-i18n="other_heading"><?php echo esc_html(cha_get_option('other_heading', 'Other Bleeding Disorders')); ?></h2></div>
      <div class="grid grid-2">
        <div class="type-card" data-reveal><div class="type-card-icon"><svg class="drop" viewBox="0 0 56 64" aria-hidden="true"><path d="M28 4 C 16 24, 8 38, 8 48 C 8 58, 18 64, 28 64 C 38 64, 48 58, 48 48 C 48 38, 40 24, 28 4 Z" fill="#6A2C91"/><ellipse cx="20" cy="32" rx="4" ry="7" fill="rgba(255,255,255,0.4)"/></svg></div><div class="type-card-body"><h3 data-i18n="other_rare_title"><?php echo esc_html(cha_get_option('other_1_title', 'Rare Factor Deficiencies')); ?></h3><p data-i18n="other_rare_desc"><?php echo esc_html(cha_get_option('other_1_desc', 'Deficiencies in factors I, II, V, VII, X, XI, XII and XIII. Each requires specific diagnosis and treatment.')); ?></p></div></div>
        <div class="type-card" data-reveal><div class="type-card-icon"><svg class="drop" viewBox="0 0 56 64" aria-hidden="true"><path d="M28 4 C 16 24, 8 38, 8 48 C 8 58, 18 64, 28 64 C 38 64, 48 58, 48 48 C 48 38, 40 24, 28 4 Z" fill="#B45309"/><ellipse cx="20" cy="32" rx="4" ry="7" fill="rgba(255,255,255,0.4)"/></svg></div><div class="type-card-body"><h3 data-i18n="other_platelet_title"><?php echo esc_html(cha_get_option('other_2_title', 'Platelet Function Disorders')); ?></h3><p data-i18n="other_platelet_desc"><?php echo esc_html(cha_get_option('other_2_desc', "Conditions where platelets don't work properly, leading to bleeding despite normal platelet counts.")); ?></p></div></div>
      </div>
      <p style="text-align:center;margin-top:var(--s-6);color:var(--c-muted)" data-i18n="other_more"><?php echo esc_html(cha_get_option('other_footer', 'For more information on any bleeding disorder, contact our team or visit a treatment centre.')); ?></p>
    </div></section>

  </main>

  <?php get_footer(); ?>
